name: Documentation Request
description: Suggest new documentation or improvements
title: "[Docs]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting documentation improvements!

  - type: textarea
    id: problem
    attributes:
      label: What's Missing or Unclear?
      description: Describe what documentation is needed or what's confusing.
      placeholder: I couldn't find information about...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested Content
      description: What would you like to see documented?
      placeholder: It would help to have a guide that explains...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Documentation Type
      options:
        - Tutorial (learning-oriented)
        - How-To Guide (task-oriented)
        - Concept (understanding-oriented)
        - Reference (information-oriented)
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to write this documentation
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or examples.
    validations:
      required: false
